#cloud-config

hostname: docker01
create_hostname_file: true
fqdn: docker01.lan

users:
  - name: user
    uid: 1000
    groups: sudo, adm
    shell: /bin/bash
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 YOURPUBKEY you@client

timezone: Europe/Berlin

# https://stackoverflow.com/questions/67741343/azure-cloud-init-failed-to-install-packages
apt:
  preserve_sources_list: true
  conf: |
    Acquire::Retries "60";
    DPkg::Lock::Timeout "60";
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - acl
  - ansible
  - apt-transport-https
  - curl
  - gnupg
  - htop
  - needrestart
  - qemu-guest-agent
  - rsync
  - sudo
  - systemd-timesyncd
  - unzip
  - vim
  - wget

runcmd:
  # remove unneeded packages
  - apt purge -y debsecan telnet rpcbind inetutils-telnet
  # harden ssh
  - sed -i 's/[#]*PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - systemctl reload ssh
  # install docker compose
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
  - apt update && apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # disable cloudinit on subsequent boots https://cloudinit.readthedocs.io/en/latest/howto/disable_cloud_init.html
  - touch /etc/cloud/cloud-init.disabled

mounts:
  - [tmpfs, /dev/shm, tmpfs, "defaults,nosuid,nodev,noexec", "0", "0"]
  - [tmpfs, /tmp, tmpfs, "defaults,nosuid,nodev,noexec", "0", "0"]

swap:
  filename: /swap.img
  size: 3G
  maxsize: 3G

# validate: cloud-init schema -c cloud-init.yml
# log on provisioned VM: /var/log/cloud-init-output.log
